layout: sidebar
style: dark

plugins:
  - jekyll-github-metadata
  - jekyll-feed

permalink: /:year/:month/:day/:title/

repository: "ItsASine/itsasine.github.io"

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

topics:
  - name: Protractor
    description: Learn enough to contribute more on stack exchange as an expert
  - name: SAS & R
    description: Extend schoolwork into actual real-world skills
  - name: Angular & D3.js
    description: Tinker with frontend frameworks and data viz
